[Refactor] Rename project, update docs
Big-Life-Lab/recodeflow pull request #4
Opened 2020-11-10 22:04 UTC by LurN

2020-11-10 22:06 UTC, LurN commented on DESCRIPTION
> +Title: Recode documents to PMML
I'm not sure how we should rephrase this. Or should we just use the same phrasing?
`Converting recodeflow Documents to PMML`?

same question for the first line in the `R/pmml.R` file.
What do you think?

2020-11-13 12:40 UTC, yulric requested changes

2020-11-13 12:40 UTC, yulric commented on DESCRIPTION
> +Title: Recode variable and variable details to PMML
The title should probably be,
Contains functions to interface with variables details sheets including recoding variables and convverting them to PMML

2020-11-16 13:07 UTC, yulric approved these changes

2020-11-16 20:28 UTC, merged