Draft specification for labels
Big-Life-Lab/recodeflow pull request #45
Opened 2024-11-18 19:45 UTC by DougManuel

The PR has specifications for refactoring labels to address the approach of moving labels out of rec_with_table(). Further, we have little use of labels and metadata, but this is a priority feature.

There is a clearer and more consistent approach to variable labels. I propose we should extend the 'labelled' library, and there are a few ways to do so.

2024-11-21 18:29 UTC, yulric requested changes
The document is pretty good but missing more text about what's in scope for the library.

2024-11-21 18:29 UTC, yulric commented on docs/labels.qmd
> +- Follow the labelled library approach. All labelled functions should work with recodeflow.
I would add a sub-section here about which challenges mentioned above recodeflow will tackle and which ones are out of scope.

2025-02-16 12:24 UTC, DougManuel commented on docs/labels.qmd
> +Adding support for labels in recodeflow will enhance data clarity and usability by providing descriptive metadata for variables, ensuring consistent interpretation across analyses. This feature will
I modified by introducing the "framework" of worksheets and S3 objects. I am concerned this may be getting technical in the intro, but the clarity is helpful.

2025-02-16 12:24 UTC, DougManuel commented on docs/labels.qmd
> +1. Facilitating data sharing and collaboration by providing clear documentation of variable meanings and valid values.
An example of missing data is added.

2025-02-18 11:16 UTC, DougManuel commented
I wrote a new version of the scope document. It hopefully addresses the comments, but unfortunately, it requires a new review.

The main body is a higher-level scope. An extensive appendix serves as a reference and explanation. That appendix was developed discussion with a LLM. References are included.

2025-02-22 17:36 UTC, yulric requested changes
This new version is way better but I would include more code examples exploring some of your statements. In addition, a lot of what you said in the appendix is actually really useful and should be brought back into the main document. Finally, there are some formatting issues that I can fix.

If you want to address my comments, I can then refactor the document to:

1. Fix the formatting issues
2. Bring the appendix text into the main document
3. Write supporting code examples

2025-02-22 17:36 UTC, yulric commented on docs/labels.qmd
> +-   **Clear specification for missing in metadata:** The specification will clarify how to denote missing values in `variables.csv` or `variable_details.csv`. For example, we may decide that within t
The sheets already have a way of representing tagged NA values by using NA::a, NA::b. Were you thinking of changing that?

2025-02-22 17:36 UTC, yulric commented on docs/labels.qmd
> +-   **Short and long variable labels:** Many datasets distinguish between a short label (a brief name) and a longer description. For example, a variable BMI might have a short label “Body Mass Index”
Examples of codebook standards and IPUMS metadata?

2025-02-22 17:36 UTC, yulric commented on docs/labels.qmd
> +-   **Preservation of metadata in transformations:** We will aim for labels to survive through data transformations as much as logically possible. For instance:
Can you provide code examples of how you imaging this would work for each transformation type? Would we override the  dplyr's mutate method to preserve labels? Would we have a separate function that does this?

2025-04-01 10:06 UTC, DougManuel commented on docs/labels.qmd
> +-   **Facilitate collaboration**: Store metadata in human-readable CSV sidecars (`variables` and `variable_details`) for project teams, including those who are not R users.
The CSV files (variables.csv and variable_details.csv) are central to the recodeflow system, not supplementary. In most contexts, let's replace "sidecar" with "metadata files" or "metadata."

2025-04-01 10:12 UTC, DougManuel commented on docs/labels.qmd
> +-   **Plan for future needs**: Align with existing R ecosystem packages and keep open the possibility of supporting DDI, LinkML, or extended role-based metadata in subsequent releases.
I am not sure what I intended. I've deleted the reference.

2025-04-01 10:40 UTC, DougManuel commented on docs/labels.qmd
> +The label system in `recodeflow` will rely on **existing standards** from packages like `` `haven` `` and `` `labelled` ``: - Use `attr(x, "label")` to store the variable label (e.g., `"Age of respon
I've updated this section to be more focused and clear that our preferred approach would be `haven`.

Example of updated text

```
```{r}
# Sample PBC dataset
data <- data.frame(
  id = 1:5,
  status = c(0, 1, 2, 0, 2)
)

# NOT RECOMMENDED: Base R approach
# attr(data$status, "label") <- "Patient status"
# attr(data$status, "labels") <- c("Censored" = 0, "Transplant" = 1, "Dead" = 2)

# RECOMMENDED: Using `haven` package
library(haven)
data$status <- labelled(
  data$status,
  labels = c("Censored" =.0, "Transplant" = 1, "Dead" = 2),
  label = "Patient status"
)

# ALTERNATIVELY: Using `labelled` package
library(labelled)
data <- set_variable_labels(data, status = "Patient status")
data$status <- set_value_labels(data$status,
                               "Censored" = 0,
                               "Transplant" = 1,
                               "Dead" = 2)
```

2025-04-01 11:53 UTC, DougManuel commented on docs/labels.qmd
> +``` r
Corrected.

2025-04-01 11:54 UTC, DougManuel commented on docs/labels.qmd
> +data <- set_variable_labels(data, status = "Patient status")
Agree.

2025-04-01 12:08 UTC, DougManuel commented on docs/labels.qmd
> +-   **Avoiding data copies:** In R, adding or modifying attributes to a vector can sometimes trigger a copy of that vector in memory. To mitigate this, `recodeflow` will try to set labels at the time
Reference added. Also clarity edits.

2025-04-01 13:39 UTC, DougManuel commented on docs/labels.qmd
> +-   **Efficient lookup and manipulation:** Functions to get or set labels will be optimized to avoid unnecessary data scanning. Retrieving a label should be near O(1) (constant time) since it can dir
Instead, I've strengthened the statement and added references. I could provide code, but it seems better suited to the specifications.

2025-04-01 13:44 UTC, DougManuel commented on docs/labels.qmd
> +-   **Clear specification for missing in metadata:** The specification will clarify how to denote missing values in `variables.csv` or `variable_details.csv`. For example, we may decide that within t
No. Well, tagged NA requires a review since the approach has gained better support in R. However, we seem still on mark. I expect greatest effort should be adding vignettes for tagged NA.

2025-04-01 13:57 UTC, DougManuel commented on docs/labels.qmd
> +-   **Short and long variable labels:** Many datasets distinguish between a short label (a brief name) and a longer description. For example, a variable BMI might have a short label “Body Mass Index”
I removed this statement.

2025-04-01 14:05 UTC, DougManuel commented on docs/labels.qmd
> +-   **Preservation of metadata in transformations:** We will aim for labels to survive through data transformations as much as logically possible. For instance:
I really don't know! 🤷 There is increasing awareness of this challenging issue within the data science communities. I was mostly flagging the issue, and we may want to leave this for future updates.

2025-04-03 19:48 UTC, yulric commented
@DougManuel I've added a new file `docs/new-labels.qmd` that is a revised version of the labels scope that combined everything in the main and appendix sections of your document. Can you take a look?

2025-04-04 16:27 UTC, DougManuel commented
It looks good and is ready to go. Merge away.

2025-04-04 16:29 UTC, merged